version: '3.1'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'content_manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  recommender-service:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/recommender-service
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload
    env_file:
      - .env
    tty: true
    restart: always
    depends_on:
      - mysql